"""
Data models for the Phase 1 agentic pipeline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import pandas as pd

from qframe.factor_harness import DEFAULT_OOS_START
from qframe.factor_harness.walkforward import WalkForwardResult


@dataclass
class ResearchSpec:
    """
    Human-provided research specification — the starting point for each loop run.

    Args:
        factor_domain:        Category to explore, e.g. 'momentum', 'mean_reversion',
                              'quality', 'volatility', 'value'.
        universe_description: Plain English, e.g. 'S&P 500 large-cap US equities'.
        oos_start:            Walk-forward OOS period start date.
        constraints:          Hard rules the factor must satisfy, e.g.
                              ['OHLCV data only', 'no look-ahead'].
    """
    factor_domain: str
    universe_description: str = "S&P 500 large-cap US equities (survivorship-biased, Phase 0)"
    oos_start: str = DEFAULT_OOS_START
    constraints: list[str] = field(default_factory=lambda: [
        "Use only daily adjusted CLOSE prices — no Open, High, Low, or Volume available",
        "No look-ahead bias — at date t, use only prices up to and including t",
        "Must be computable from the `prices` (Close only) DataFrame alone",
    ])


@dataclass
class HypothesisSpec:
    """
    A single factor hypothesis as generated by the Synthesis agent.

    Args:
        name:             Short snake_case identifier, e.g. 'volatility_reversal'.
        description:      One sentence plain English.
        rationale:        Economic mechanism — why should this predict returns?
        mechanism_score:  1–5 (1=data mining, 5=causal evidence). See schema.
        factor_type:      Category tag.
    """
    name: str
    description: str
    rationale: str
    mechanism_score: int
    factor_type: str


# Verdict constants
VERDICT_PASS = "PASS"
VERDICT_WEAK = "WEAK"
VERDICT_FAIL = "FAIL"
VERDICT_ERROR = "ERROR"


@dataclass
class IterationResult:
    """
    Full output of one pipeline iteration.

    Args:
        hypothesis:           The generated hypothesis.
        code:                 The generated Python factor code (str).
        wf_result:            Walk-forward result, or None if execution failed.
        analysis:             Free-text interpretation from the Analysis agent.
        verdict:              PASS / WEAK / FAIL / ERROR.
        kb_hypothesis_id:     SQLite row id for the hypothesis.
        kb_implementation_id: SQLite row id for the implementation.
        kb_result_id:         SQLite row id for the backtest result (None on error).
        error:                Error message if execution failed.
    """
    hypothesis: HypothesisSpec
    code: str
    wf_result: Optional[WalkForwardResult]
    analysis: str
    verdict: str
    kb_hypothesis_id: int
    kb_implementation_id: int
    kb_result_id: Optional[int]
    error: Optional[str] = None

    def print_summary(self) -> None:
        print(f"\n{'='*60}")
        print(f"Factor: {self.hypothesis.name}")
        print(f"Verdict: {self.verdict}")
        print(f"Description: {self.hypothesis.description}")
        if self.wf_result:
            s = self.wf_result.summary()
            print(f"\nMetrics (OOS {s['oos_start']} → {s['oos_end']}):")
            print(f"  IC        = {s['ic']:.4f}")
            print(f"  ICIR      = {s['icir']:.3f}")
            print(f"  Net IC    = {s['net_ic']:.4f}")
            print(f"  Sharpe    = {s['sharpe']:.3f}")
            print(f"  Turnover  = {s['turnover']:.1%}/day")
            hl = s['decay_halflife']
            hl_str = f"{hl:.1f}d" if pd.notna(hl) else "n/a"
            print(f"  Half-life = {hl_str}")
        if self.error:
            # Show only the final error line, not the full traceback
            error_lines = [ln for ln in self.error.strip().splitlines() if ln.strip()]
            last_line = error_lines[-1] if error_lines else "(empty error)"
            print(f"\nError: {last_line}")
        print(f"\nAnalysis:\n{self.analysis}")
        print(f"{'='*60}")
